<?php
namespace Opencart\Admin\Controller\Extension\Linnworks\Module;
class Linnworks extends \Opencart\System\Engine\Controller {
 private array $error=[];
 private array $keys=['status','application_id','application_secret','token','auth_url','timeout','public_base_url','channel_name','channel_friendly_name','dry_run','stock_location_id','price_authority','price_field','identifier_code','model_normalisation','readiness_target','source','sub_source','store_code','store_name','export_status_id','complete_status_id'];
 public function index():void{
  $this->load->language('extension/linnworks/module/linnworks');$this->document->setTitle($this->language->get('heading_title'));$this->load->model('setting/setting');$this->load->model('extension/linnworks/module/linnworks');
  if(($this->request->server['REQUEST_METHOD']??'')==='POST'&&$this->validate()){$s=$this->request->post;$s['module_linnworks_status']=1;$s['module_linnworks_dry_run']=1;$this->model_setting_setting->editSetting('module_linnworks',$s);$this->session->data['success']=$this->language->get('text_success');$this->response->redirect($this->url->link('extension/linnworks/module/linnworks','user_token='.$this->session->data['user_token'],true));}
  foreach($this->keys as $k){$n='module_linnworks_'.$k;$data[$n]=$this->request->post[$n]??$this->config->get($n);} $defaults=['auth_url'=>'https://api.linnworks.net/api/Auth/AuthorizeByApplication','timeout'=>30,'channel_name'=>'GBAPPLIANCESOPENCART','channel_friendly_name'=>'GB Appliances OpenCart','price_authority'=>'opencart','price_field'=>'purchase_price','identifier_code'=>'EAN','model_normalisation'=>'optional_n_prefix','readiness_target'=>90,'source'=>'Employee Store','sub_source'=>'OpenCart'];foreach($defaults as $k=>$v){$n='module_linnworks_'.$k;if(!$data[$n])$data[$n]=$v;}
  $data['heading_title']=$this->language->get('heading_title');$data['success']=$this->session->data['success']??'';unset($this->session->data['success']);$data['error_warning']=$this->error['warning']??'';$data['dashboard']=$this->model_extension_linnworks_module_linnworks->dashboard();$data['issues']=$this->model_extension_linnworks_module_linnworks->issues(['limit'=>8]);$data['history_rows']=$this->model_extension_linnworks_module_linnworks->scanHistory(8);$data['code_types']=$this->model_extension_linnworks_module_linnworks->codeTypes();$data['stock_locations']=[];try{if($this->hasCredentials($data))$data['stock_locations']=$this->model_extension_linnworks_module_linnworks->locations($this->settingsFromData($data));}catch(\Throwable $e){$data['location_error']=$e->getMessage();}
  $t='user_token='.$this->session->data['user_token'];foreach(['test','locations','scan','diagnostics','results','history','export'] as $a)$data[$a]=$this->url->link('extension/linnworks/module/linnworks|'.$a,$t,true);$data['save']=$this->url->link('extension/linnworks/module/linnworks',$t,true);$data['back']=$this->url->link('marketplace/extension',$t.'&type=module');$data['header']=$this->load->controller('common/header');$data['column_left']=$this->load->controller('common/column_left');$data['footer']=$this->load->controller('common/footer');$this->response->setOutput($this->load->view('extension/linnworks/module/linnworks',$data));
 }
 public function test():void{$this->json(function(){return ['success'=>'Connected successfully','session'=>$this->model_extension_linnworks_module_linnworks->authorize($this->posted())];});}
 public function locations():void{$this->json(function(){return ['success'=>'Locations retrieved','locations'=>$this->model_extension_linnworks_module_linnworks->locations($this->posted())];});}
 public function diagnostics():void{$this->json(function(){$c=[['name'=>'PHP cURL','status'=>function_exists('curl_init')],['name'=>'OpenSSL','status'=>extension_loaded('openssl')]];try{$a=$this->model_extension_linnworks_module_linnworks->authorize($this->posted());$c[]=['name'=>'Linnworks authentication','status'=>true,'detail'=>$a['Locality']??''];}catch(\Throwable $e){$c[]=['name'=>'Linnworks authentication','status'=>false,'detail'=>$e->getMessage()];}return ['success'=>'Diagnostics complete','checks'=>$c];});}
 public function scan():void{$this->json(function(){return ['success'=>'Catalogue scan complete','scan'=>$this->model_extension_linnworks_module_linnworks->scan((string)($this->config->get('module_linnworks_identifier_code')?:'EAN'))];});}
 public function results():void{$this->load->model('extension/linnworks/module/linnworks');$f=['scan_id'=>(int)($this->request->get['scan_id']??0),'severity'=>(string)($this->request->get['severity']??''),'category'=>(string)($this->request->get['category']??''),'ready'=>(string)($this->request->get['ready']??''),'search'=>trim((string)($this->request->get['search']??'')),'limit'=>100];$data=['filters'=>$f,'scan'=>$this->model_extension_linnworks_module_linnworks->scanSummary($f['scan_id']),'products'=>$this->model_extension_linnworks_module_linnworks->scanProducts($f),'issues'=>$this->model_extension_linnworks_module_linnworks->issues($f)];$t='user_token='.$this->session->data['user_token'];$data['back']=$this->url->link('extension/linnworks/module/linnworks',$t);$data['export']=$this->url->link('extension/linnworks/module/linnworks|export',$t.'&scan_id='.(int)($data['scan']['scan_id']??0));$data['header']=$this->load->controller('common/header');$data['column_left']=$this->load->controller('common/column_left');$data['footer']=$this->load->controller('common/footer');$this->response->setOutput($this->load->view('extension/linnworks/module/linnworks_results',$data));}
 public function history():void{$this->load->model('extension/linnworks/module/linnworks');$data['scans']=$this->model_extension_linnworks_module_linnworks->scanHistory(100);$t='user_token='.$this->session->data['user_token'];$data['results_base']=$this->url->link('extension/linnworks/module/linnworks|results',$t);$data['back']=$this->url->link('extension/linnworks/module/linnworks',$t);$data['header']=$this->load->controller('common/header');$data['column_left']=$this->load->controller('common/column_left');$data['footer']=$this->load->controller('common/footer');$this->response->setOutput($this->load->view('extension/linnworks/module/linnworks_history',$data));}
 public function export():void{$this->load->model('extension/linnworks/module/linnworks');$rows=$this->model_extension_linnworks_module_linnworks->scanProducts(['scan_id'=>(int)($this->request->get['scan_id']??0),'limit'=>100000]);$o=fopen('php://temp','w+');fputcsv($o,['Product ID','Name','Model','Normalised Model','Identifier','Price','Quantity','Score','Ready']);foreach($rows as $r)fputcsv($o,[$r['product_id'],$r['name'],$r['model'],$r['normalised_model'],$r['identifier_value'],$r['price'],$r['quantity'],$r['readiness_score'],$r['ready_for_sync']]);rewind($o);$this->response->addHeader('Content-Type: text/csv');$this->response->addHeader('Content-Disposition: attachment; filename="linnworks-scan.csv"');$this->response->setOutput(stream_get_contents($o));}
 public function install():void{if($this->user->hasPermission('modify','extension/linnworks/module/linnworks')){$this->load->model('extension/linnworks/module/linnworks');$this->model_extension_linnworks_module_linnworks->install();}}
 public function uninstall():void{}
 private function json(callable $fn):void{$this->load->language('extension/linnworks/module/linnworks');try{if(!$this->user->hasPermission('modify','extension/linnworks/module/linnworks'))throw new \RuntimeException($this->language->get('error_permission'));$this->load->model('extension/linnworks/module/linnworks');$r=$fn();}catch(\Throwable $e){$r=['error'=>$e->getMessage()];}$this->response->addHeader('Content-Type: application/json');$this->response->setOutput(json_encode($r));}
 private function posted():array{return ['application_id'=>(string)($this->request->post['module_linnworks_application_id']??$this->config->get('module_linnworks_application_id')),'application_secret'=>(string)($this->request->post['module_linnworks_application_secret']??$this->config->get('module_linnworks_application_secret')),'token'=>(string)($this->request->post['module_linnworks_token']??$this->config->get('module_linnworks_token')),'auth_url'=>(string)($this->request->post['module_linnworks_auth_url']??$this->config->get('module_linnworks_auth_url')),'timeout'=>(int)($this->request->post['module_linnworks_timeout']??30)];}
 private function settingsFromData(array $d):array{return ['application_id'=>$d['module_linnworks_application_id'],'application_secret'=>$d['module_linnworks_application_secret'],'token'=>$d['module_linnworks_token'],'auth_url'=>$d['module_linnworks_auth_url'],'timeout'=>$d['module_linnworks_timeout']];}
 private function hasCredentials(array $d):bool{return !empty($d['module_linnworks_application_id'])&&!empty($d['module_linnworks_application_secret'])&&!empty($d['module_linnworks_token']);}
 protected function validate():bool{if(!$this->user->hasPermission('modify','extension/linnworks/module/linnworks'))$this->error['warning']=$this->language->get('error_permission');return !$this->error;}
}
