<?php
namespace Opencart\Admin\Model\Extension\Linnworks\Module;
class Linnworks extends \Opencart\System\Engine\Model {
 public function install():void{
  $sql=[];
  $sql[]="CREATE TABLE IF NOT EXISTS `".DB_PREFIX."linnworks_account` (`account_id` int NOT NULL AUTO_INCREMENT,`sid_registration` varchar(36) NOT NULL DEFAULT '',`account_name` varchar(128) NOT NULL DEFAULT '',`email` varchar(255) NOT NULL DEFAULT '',`authorization_token_hash` varchar(255) NOT NULL DEFAULT '',`status` tinyint(1) NOT NULL DEFAULT 1,`date_added` datetime NOT NULL,`date_modified` datetime NOT NULL,PRIMARY KEY(`account_id`),UNIQUE KEY `sid_registration`(`sid_registration`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
  $sql[]="CREATE TABLE IF NOT EXISTS `".DB_PREFIX."linnworks_mapping` (`mapping_id` int NOT NULL AUTO_INCREMENT,`product_id` int NOT NULL,`stock_item_id` varchar(36) NOT NULL DEFAULT '',`ean` varchar(64) NOT NULL DEFAULT '',`model` varchar(64) NOT NULL DEFAULT '',`sku` varchar(64) NOT NULL DEFAULT '',`status` varchar(32) NOT NULL DEFAULT 'pending',`date_added` datetime NOT NULL,`date_modified` datetime NOT NULL,PRIMARY KEY(`mapping_id`),UNIQUE KEY `product_id`(`product_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
  $sql[]="CREATE TABLE IF NOT EXISTS `".DB_PREFIX."linnworks_queue` (`queue_id` bigint NOT NULL AUTO_INCREMENT,`job_type` varchar(64) NOT NULL,`entity_id` varchar(64) NOT NULL,`payload` mediumtext,`status` varchar(24) NOT NULL DEFAULT 'pending',`attempts` int NOT NULL DEFAULT 0,`date_added` datetime NOT NULL,`date_modified` datetime NOT NULL,PRIMARY KEY(`queue_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
  $sql[]="CREATE TABLE IF NOT EXISTS `".DB_PREFIX."linnworks_log` (`log_id` bigint NOT NULL AUTO_INCREMENT,`level` varchar(16) NOT NULL,`area` varchar(32) NOT NULL,`message` text NOT NULL,`context` mediumtext,`date_added` datetime NOT NULL,PRIMARY KEY(`log_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
  $sql[]="CREATE TABLE IF NOT EXISTS `".DB_PREFIX."linnworks_channel_config` (`config_id` int NOT NULL AUTO_INCREMENT,`account_id` int NOT NULL,`config_key` varchar(128) NOT NULL,`config_value` text,`date_modified` datetime NOT NULL,PRIMARY KEY(`config_id`),UNIQUE KEY `account_key`(`account_id`,`config_key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
  foreach($sql as $q)$this->db->query($q);
 }
 public function uninstall():void{}
 public function authorize(array $s):array{return $this->request('POST',$s['auth_url'],['ApplicationId'=>trim($s['application_id']),'ApplicationSecret'=>trim($s['application_secret']),'Token'=>trim($s['token'])],'',(int)$s['timeout']);}
 public function locations(array $s):array{$a=$this->authorize($s);$server=rtrim((string)($a['Server']??''),'/');$token=(string)($a['Token']??'');if(!$server||!$token)throw new \RuntimeException('Authentication did not return Server and Token.');return $this->request('GET',$server.'/api/Inventory/GetStockLocations',null,$token,(int)$s['timeout']);}
 public function scan():array{$p=DB_PREFIX.'product';return ['total'=>(int)$this->db->query("SELECT COUNT(*) total FROM `$p`")->row['total'],'missing_ean'=>(int)$this->db->query("SELECT COUNT(*) total FROM `$p` WHERE TRIM(`ean`)='' ")->row['total'],'missing_model'=>(int)$this->db->query("SELECT COUNT(*) total FROM `$p` WHERE TRIM(`model`)='' ")->row['total'],'duplicate_ean'=>(int)$this->db->query("SELECT COUNT(*) total FROM (SELECT ean FROM `$p` WHERE TRIM(ean)<>'' GROUP BY ean HAVING COUNT(*)>1) x")->row['total'],'duplicate_model'=>(int)$this->db->query("SELECT COUNT(*) total FROM (SELECT model FROM `$p` WHERE TRIM(model)<>'' GROUP BY model HAVING COUNT(*)>1) x")->row['total']];}
 public function counts():array{$o=[];foreach(['mapping','queue','log'] as $t){try{$o[$t]=(int)$this->db->query("SELECT COUNT(*) total FROM `".DB_PREFIX."linnworks_$t`")->row['total'];}catch(\Throwable $e){$o[$t]=0;}}return $o;}
 public function logs():array{try{return $this->db->query("SELECT * FROM `".DB_PREFIX."linnworks_log` ORDER BY log_id DESC LIMIT 25")->rows;}catch(\Throwable $e){return [];}}
 public function log(string $level,string $area,string $message,array $context=[]):void{foreach($context as $k=>$v)if(preg_match('/token|secret|password/i',$k))$context[$k]='[REDACTED]';$this->db->query("INSERT INTO `".DB_PREFIX."linnworks_log` SET level='".$this->db->escape($level)."',area='".$this->db->escape($area)."',message='".$this->db->escape($message)."',context='".$this->db->escape(json_encode($context))."',date_added=NOW()");}
 private function request(string $method,string $url,?array $payload,string $token,int $timeout):array{if(!function_exists('curl_init'))throw new \RuntimeException('PHP cURL is not installed.');$ch=curl_init($url);$h=['Accept: application/json','Content-Type: application/json'];if($token)$h[]='Authorization: '.$token;$o=[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>$h,CURLOPT_CONNECTTIMEOUT=>$timeout,CURLOPT_TIMEOUT=>$timeout,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2];if($method==='POST'){$o[CURLOPT_POST]=true;$o[CURLOPT_POSTFIELDS]=json_encode($payload??[]);}curl_setopt_array($ch,$o);$body=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);if($body===false||$err)throw new \RuntimeException('HTTPS request failed: '.$err);$j=json_decode($body,true);if($code<200||$code>=300)throw new \RuntimeException('Linnworks HTTP '.$code.': '.substr((string)($j['Message']??$j['message']??$body),0,500));if(!is_array($j))throw new \RuntimeException('Linnworks returned invalid JSON.');return $j;}
}
